config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'tasks', to: 'tasks#index'
  # get 'tasks/new', to: 'tasks#new', as: :new_task
  # post 'tasks', to: 'tasks#create'
  # get 'tasks/:id', to: 'tasks#show', as: :task
  # patch 'tasks/:id', to: 'tasks#update'
  # delete 'tasks/:id', to: 'tasks#destroy'

  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to tasks_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    # no need for app/views/restaurants/destroy.html.erb
    redirect_to tasks_path
  end


  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<div class="d-flex justify-content-center">
<div class="card p-5">
<h1>MY TASKS</h1>
<ul>
  <% @tasks.each do |task| %>
    <li class="justify-content-center list-group-item list-group-item-action"><%= link_to task.title, task_path(task) %></li>
  <% end %>
</ul>
<%= link_to "Create task", new_task_path %>
</div>
</div>

app/views/tasks/new.html.erb
  <div class="m-9">
    <%= form_for(@task) do |f| %>
    <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.text_field :details %>
      <%= f.submit %>
    <% end %>

    <%= link_to tasks_path do %>
      <button type="button" class="btn btn-primary">Back to list</button>
    <% end %>
  </div>

app/views/tasks/show.html.erb
<div class="d-flex justify-content-center">
<div class="p-5 card mx-auto text-center" style="width: 18rem;">
<h2><%= @task.title %></h2>

<p><%= @task.details %></p>

<%#= link_to "Delete #{@task.title}",
            task_path(@task),
            method: :delete,
            data: { confirm: "Are you sure?" } %>

<%= link_to task_path(@task), method: :delete %>


<%= link_to tasks_path do %>
<button type="button" class="btn btn-primary">Back to list</button>
<% end %>
</div>
</div>